// Generated by brand/scripts/build.mjs - do not edit.
package app.scrin.brand

import androidx.compose.ui.graphics.Color

object BrandTokens {
    val ink = Color(0xFF002327)
    val inkHi = Color(0xFF06393C)
    val inkRim = Color(0xFF285558)
    val ivory = Color(0xFFEDF8F5)
    val lagoonBright = Color(0xFF37E1C4)
    val lagoonDeep = Color(0xFF007463)
    val inkText = Color(0xFF062427)
    const val ACCENT_HUE = 178f
    const val ACCENT_CHROMA = 0.14f
}

object BrandLight {
    val bgCanvas = Color(0xFFF6FBFA)
    val bgSurface = Color(0xFFFFFFFF)
    val bgSubtle = Color(0xFFE9F3F0)
    val fgDefault = Color(0xFF111816)
    val fgMuted = Color(0xFF545D5B)
    val borderDefault = Color(0xFFCAD3D1)
    val borderFocus = Color(0xFF007B69)
    val accentSolid = Color(0xFF007B69)
    val accentSolidHover = Color(0xFF006E5E)
    val accentText = Color(0xFF006455)
    val accentSubtle = Color(0xFFDAF6EE)
    val fgOnAccent = Color(0xFFFCFCFC)
}

object BrandDark {
    val bgCanvas = Color(0xFF0A110F)
    val bgSurface = Color(0xFF141B19)
    val bgSubtle = Color(0xFF1E2624)
    val fgDefault = Color(0xFFEEF3F2)
    val fgMuted = Color(0xFFA4ADAB)
    val borderDefault = Color(0xFF373F3D)
    val borderFocus = Color(0xFF00CDB1)
    val accentSolid = Color(0xFF00CDB1)
    val accentSolidHover = Color(0xFF43D9BE)
    val accentText = Color(0xFF71E2CA)
    val accentSubtle = Color(0xFF0B221D)
    val fgOnAccent = Color(0xFF0C1312)
}
