// Regenerates packages/sdk/openapi.json (from the API's routes) and src/schema.d.ts
// (openapi-typescript). `--check` fails when either differs from the committed copy.
import { execFileSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import * as prettier from 'prettier';

const root = fileURLToPath(new URL('..', import.meta.url));
const apiDir = fileURLToPath(new URL('../../../apps/api/', import.meta.url));
const specPath = `${root}openapi.json`;
const typesPath = `${root}src/schema.d.ts`;
const check = process.argv.includes('--check');

const HEADER =
  '/* eslint-disable */\n' +
  '// Generated by packages/sdk/scripts/generate.mjs from apps/api. Do not edit.\n' +
  '// Regenerate: pnpm --filter @scrin/sdk generate\n\n';

const rawSpec = execFileSync(
  process.execPath,
  ['--experimental-strip-types', '--no-warnings', 'scripts/export-openapi.ts'],
  { cwd: apiDir, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 },
);
const ast = await openapiTS(JSON.parse(rawSpec), { exportType: true, alphabetize: true });

// Same formatting as `pnpm format`, so generated files pass format:check.
const fmt = async (text, filepath) => {
  const options = (await prettier.resolveConfig(filepath)) ?? {};
  return prettier.format(text, { ...options, plugins: [], filepath });
};
const spec = await fmt(rawSpec, specPath);
const types = await fmt(HEADER + astToString(ast), typesPath);

const normalise = (s) => s.replace(/\r\n/g, '\n');
async function readOr(path) {
  try {
    return normalise(await readFile(path, 'utf8'));
  } catch {
    return '';
  }
}

if (check) {
  const drift = [];
  if ((await readOr(specPath)) !== normalise(spec)) drift.push('openapi.json');
  if ((await readOr(typesPath)) !== normalise(types)) drift.push('src/schema.d.ts');
  if (drift.length > 0) {
    process.stderr.write(
      `SDK drift: ${drift.join(', ')} out of date with apps/api.\nRun: pnpm --filter @scrin/sdk generate\n`,
    );
    process.exit(1);
  }
  process.stdout.write('SDK is up to date with apps/api\n');
} else {
  await writeFile(specPath, spec, 'utf8');
  await writeFile(typesPath, types, 'utf8');
  process.stdout.write(`wrote ${specPath} and ${typesPath}\n`);
}
