#!/usr/bin/env node
// scrin brand pack generator. Pure Node (no deps). Writes tokens, contrast pairs, SVG masters,
// concept SVGs, Android vector/AVD XML, motion outputs (CSS, animated SVG, Motion TS), the
// comparison sheet and demo HTML. Rasters (PNG/WebP/ICO) come from render.mjs.
//
//   node brand/scripts/build.mjs
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { halves, microHalves, wordmark } from './geometry.mjs';
import { toHex } from './oklch.mjs';
import { HUE, CHROMA, TINT, ramps, brandColors as B, status, semantic, resolve, amoledBg } from './palette.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const written = [];
function write(rel, content) {
  const p = join(ROOT, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, content.endsWith('\n') ? content : content + '\n', 'utf8');
  written.push(rel);
}
const ok = (c) => `oklch(${c.l} ${c.c} ${c.h})`;
const motion = JSON.parse(readFileSync(join(ROOT, 'tokens/motion.tokens.json'), 'utf8'));

// ---------------------------------------------------------------- 1. tokens (DTCG 2025.10)
const dtcgColor = (c, desc) => ({
  $value: { colorSpace: 'oklch', components: [c.l, c.c, c.h], hex: c.hex },
  ...(desc ? { $description: desc } : {}),
});
const STEP_JOBS = [
  'app background', 'subtle background', 'component bg', 'component bg hover', 'component bg active',
  'subtle border', 'interactive border', 'strong border / focus ring', 'solid', 'solid hover',
  'low-contrast text', 'high-contrast text',
];
const primitives = {
  $description:
    'Layer 1 - raw ramps, generated by brand/scripts/build.mjs from palette.mjs. Components never read these; semantic tokens reference them.',
  color: { $type: 'color' },
};
for (const [name, ramp] of Object.entries(ramps)) {
  primitives.color[name] = Object.fromEntries(ramp.map((c, i) => [String(i + 1), dtcgColor(c, STEP_JOBS[i])]));
}
primitives.color.brand = Object.fromEntries(Object.entries(B).map(([k, c]) => [k, dtcgColor(c)]));
for (const theme of ['light', 'dark']) {
  for (const [k, v] of Object.entries(status[theme])) {
    primitives.color[`${k}${theme === 'dark' ? '-dark' : ''}`] = {
      3: dtcgColor(v.bg), 9: dtcgColor(v.solid), 11: dtcgColor(v.fg),
    };
  }
}
write('tokens/primitives.tokens.json', JSON.stringify(primitives, null, 2));

const semanticTokens = {
  $description: 'Layer 2 - semantic slots per theme. Themes remap only this layer.',
};
for (const theme of ['light', 'dark']) {
  const t = { $type: 'color' };
  for (const [slot, v] of Object.entries(semantic[theme])) {
    const [group, key] = slot.split('.');
    t[group] ??= {};
    t[group][key] = Array.isArray(v)
      ? { $value: `{color.${v[0]}.${v[1]}}` }
      : dtcgColor(v);
  }
  t.status = {};
  for (const k of Object.keys(status[theme])) {
    const p = `color.${k}${theme === 'dark' ? '-dark' : ''}`;
    t.status[k] = { bg: { $value: `{${p}.3}` }, solid: { $value: `{${p}.9}` }, fg: { $value: `{${p}.11}` } };
  }
  semanticTokens[theme] = t;
}
semanticTokens['dark-amoled'] = {
  $type: 'color',
  $description: 'AMOLED surface mode: only bg.canvas changes; everything else inherits dark.',
  bg: { canvas: dtcgColor(amoledBg) },
};
write('tokens/semantic.tokens.json', JSON.stringify(semanticTokens, null, 2));

// ---------------------------------------------------------------- 2. packages/ui proposal check
// Exact replica of packages/ui/src/theme/tokens.ts derivePalette for the proposed default preset.
function derivePalette(mode, surface, h, c) {
  const tint = Math.min(c, 0.2) * 0.08;
  if (mode === 'light') {
    const accentL = h > 70 && h < 160 ? 0.47 : 0.52;
    return {
      bg: [0.985, tint * 0.5, h], surface: [1, 0, h], 'surface-2': [0.955, tint, h], fg: [0.2, tint, h],
      muted: [0.47, tint, h], outline: [0.86, tint, h], accent: [accentL, Math.min(c, 0.2), h],
      'accent-fg': [0.99, 0, h], success: [0.5, 0.13, 150], warning: [0.55, 0.14, 70], danger: [0.53, 0.19, 27],
    };
  }
  const am = surface === 'amoled';
  return {
    bg: am ? [0, 0, h] : [0.17, tint, h], surface: am ? [0.13, tint, h] : [0.215, tint, h],
    'surface-2': am ? [0.18, tint, h] : [0.26, tint, h], fg: [0.96, tint * 0.5, h], muted: [0.74, tint, h],
    outline: am ? [0.3, tint, h] : [0.36, tint, h], accent: [0.76, Math.min(c, 0.17), h],
    'accent-fg': [0.18, tint, h], success: [0.77, 0.15, 150], warning: [0.82, 0.14, 80], danger: [0.72, 0.17, 25],
  };
}

// ---------------------------------------------------------------- 3. contrast pairs
const pairs = [];
const pair = (name, fg, bg, use) => pairs.push({ name, fg: typeof fg === 'string' ? fg : fg.hex, bg: typeof bg === 'string' ? bg : bg.hex, use });
for (const theme of ['light', 'dark']) {
  const r = (s) => resolve(theme, s);
  pair(`${theme}: fg.default on bg.canvas`, r('fg.default'), r('bg.canvas'), 'body');
  pair(`${theme}: fg.default on bg.surface`, r('fg.default'), r('bg.surface'), 'body');
  pair(`${theme}: fg.default on bg.subtle`, r('fg.default'), r('bg.subtle'), 'body');
  pair(`${theme}: fg.muted on bg.canvas`, r('fg.muted'), r('bg.canvas'), 'body');
  pair(`${theme}: fg.muted on bg.subtle`, r('fg.muted'), r('bg.subtle'), 'body');
  pair(`${theme}: accent.text on bg.canvas`, r('accent.text'), r('bg.canvas'), 'body');
  pair(`${theme}: accent.text on accent.subtle`, r('accent.text'), r('accent.subtle'), 'body');
  pair(`${theme}: fg.on-accent on accent.solid`, r('fg.on-accent'), r('accent.solid'), 'body');
  pair(`${theme}: fg.on-accent on accent.solid-hover`, r('fg.on-accent'), r('accent.solid-hover'), 'body');
  pair(`${theme}: border.focus on bg.canvas`, r('border.focus'), r('bg.canvas'), 'ui');
  pair(`${theme}: border.focus on bg.surface`, r('border.focus'), r('bg.surface'), 'ui');
  for (const [k, v] of Object.entries(status[theme])) {
    pair(`${theme}: status.${k}.fg on status.${k}.bg`, v.fg, v.bg, 'body');
    pair(`${theme}: status.${k}.solid on bg.canvas`, v.solid, r('bg.canvas'), 'ui');
  }
}
pair('dark-amoled: fg.default on bg.canvas', resolve('dark', 'fg.default'), amoledBg, 'body');
pair('dark-amoled: accent.solid on bg.canvas', resolve('dark', 'accent.solid'), amoledBg, 'ui');
// packages/ui default-preset proposal, as the browser paints it (channel-clipped hex).
for (const [mode, surface] of [['light', 'solid'], ['dark', 'solid'], ['dark', 'amoled']]) {
  const p = derivePalette(mode, surface, HUE, CHROMA);
  const hx = (k) => toHex(...p[k]);
  const tag = `ui-preset lagoon ${mode}/${surface}`;
  pair(`${tag}: fg on bg`, hx('fg'), hx('bg'), 'body');
  pair(`${tag}: muted on surface-2`, hx('muted'), hx('surface-2'), 'body');
  pair(`${tag}: accent-fg on accent`, hx('accent-fg'), hx('accent'), 'body');
  pair(`${tag}: accent on bg`, hx('accent'), hx('bg'), 'body');
  pair(`${tag}: accent on surface`, hx('accent'), hx('surface'), 'body');
}
// Mark / icon pairs (non-text, 3:1).
pair('icon: ivory half on ink tile', B.ivory, B.ink, 'ui');
pair('icon: lagoon half on ink tile', B['lagoon-bright'], B.ink, 'ui');
pair('icon: lagoon half on ink tile (lit corner)', B['lagoon-bright'], B['ink-hi'], 'ui');
pair('icon: ink tile on Windows light taskbar #f3f3f3', B.ink, '#f3f3f3', 'ui');
pair('icon: lagoon half on Windows dark taskbar #202020', B['lagoon-bright'], '#202020', 'ui');
pair('tray dark: ivory on taskbar #202020', B.ivory, '#202020', 'ui');
pair('tray dark: lagoon on taskbar #202020', B['lagoon-bright'], '#202020', 'ui');
pair('tray light: ink on taskbar #f3f3f3', B['ink-text'], '#f3f3f3', 'ui');
pair('tray light: lagoon-deep on taskbar #f3f3f3', B['lagoon-deep'], '#f3f3f3', 'ui');
pair('wordmark light: ink on white', B['ink-text'], '#ffffff', 'large');
pair('wordmark light: lagoon-deep i-dot on white', B['lagoon-deep'], '#ffffff', 'ui');
pair('wordmark dark: ivory on bg.canvas dark', B.ivory, resolve('dark', 'bg.canvas'), 'large');
pair('og/banner: tagline ivory on ink', B.ivory, B.ink, 'body');
pair('og/banner: muted tagline on ink', ramps['neutral-dark'][10], B.ink, 'body');
write('contrast-pairs.json', JSON.stringify({ $description: 'Generated by build.mjs. Input for scripts/contrast-gate.mjs. body 4.5 | large 3 | ui 3.', pairs }, null, 2));

// ---------------------------------------------------------------- 4. SVG masters
const VARIANTS = {
  master: { grid: 24, ...halves({ stroke: 2.75 }), scale: 0.8 }, // >= 64 px
  small: { grid: 24, ...halves({ stroke: 3 }), scale: 0.86 }, // 24-48 px
  micro: { grid: 16, ...microHalves(), scale: 1 }, // 16-20 px, pixel grid
};
const MONO_GAP = { master: 0.9, small: 1, micro: 1 };
function markGroup(v, colors, { gap = false, id = '', pathLength = false } = {}) {
  const src = gap
    ? v.grid === 16 ? microHalves({ gap: MONO_GAP.micro }) : halves({ stroke: v.stroke, gap: MONO_GAP.master })
    : v;
  const c = v.grid / 2;
  const pl = pathLength ? ' pathLength="1"' : '';
  const t = v.scale === 1 ? '' : ` transform="translate(${c} ${c}) scale(${v.scale}) translate(${-c} ${-c})"`;
  return (
    `<g${t}><g${id ? ` id="${id}"` : ''} class="scrin-mark" fill="none" stroke-width="${v.stroke}" stroke-linejoin="round">` +
    `<path class="scrin-mark__ivory" d="${src.ivory}" stroke="${colors[0]}"${pl}/>` +
    `<path class="scrin-mark__lagoon" d="${src.lagoon}" stroke="${colors[1]}"${pl}/></g></g>`
  );
}
function tileSvg(variantName, { size = 512, bg = 'ink', markColors = [B.ivory.hex, B['lagoon-bright'].hex], full = false } = {}) {
  const v = VARIANTS[variantName];
  const g = v.grid;
  const inset = full ? 0 : g / 24;
  const rx = full ? 0 : g * (5.25 / 24);
  const tile =
    bg === 'ink'
      ? `<defs><linearGradient id="t" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${B['ink-hi'].hex}"/><stop offset="0.7" stop-color="${B.ink.hex}"/></linearGradient></defs>` +
        `<rect x="${inset}" y="${inset}" width="${g - 2 * inset}" height="${g - 2 * inset}" rx="${rx}" fill="url(#t)"/>` +
          (full ? '' : `<rect class="rim" x="${inset + 0.1}" y="${inset + 0.1}" width="${g - 2 * inset - 0.2}" height="${g - 2 * inset - 0.2}" rx="${rx - 0.1}" fill="none" stroke="${B['ink-rim'].hex}" stroke-width="0.2" stroke-opacity="0.9"/>`)
      : `<rect x="${inset}" y="${inset}" width="${g - 2 * inset}" height="${g - 2 * inset}" rx="${rx}" fill="${bg}"/>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${g} ${g}" width="${size}" height="${size}" role="img" aria-label="scrin">${tile}${markGroup(v, markColors)}</svg>`;
}
function symbolSvg(variantName, colors, { gap = false, size = 512 } = {}) {
  const v = VARIANTS[variantName];
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${v.grid} ${v.grid}" width="${size}" height="${size}" role="img" aria-label="scrin">${markGroup(v, colors, { gap })}</svg>`;
}
const DARK = [B.ivory.hex, B['lagoon-bright'].hex];
const LIGHT = [B['ink-text'].hex, B['lagoon-deep'].hex];
for (const name of Object.keys(VARIANTS)) {
  write(`logo/app-icon-${name}.svg`, tileSvg(name));
  write(`logo/symbol-${name}-on-dark.svg`, symbolSvg(name, DARK));
  write(`logo/symbol-${name}-on-light.svg`, symbolSvg(name, LIGHT));
  write(`logo/symbol-${name}-mono-black.svg`, symbolSvg(name, ['#000', '#000'], { gap: true }));
  write(`logo/symbol-${name}-mono-white.svg`, symbolSvg(name, ['#fff', '#fff'], { gap: true }));
}
write('logo/app-icon-inverse.svg', tileSvg('master', { bg: B['lagoon-bright'].hex, markColors: [B.ink.hex, B.ivory.hex] }));
write('logo/app-icon-staging.svg', tileSvg('small', { bg: B['lagoon-bright'].hex, markColors: [B.ink.hex, B.ink.hex] }));

// Wordmark + lockups
const wm = wordmark({ stroke: 3 });
function wordmarkSvg(textColor, dotColor, { size = 1 } = {}) {
  const pad = 0;
  const w = wm.width + pad * 2;
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${-pad} ${wm.top - pad} ${w} ${wm.height + pad * 2}" width="${w * 10 * size}" height="${(wm.height + pad * 2) * 10 * size}" role="img" aria-label="scrin">` +
    `<g fill="none" stroke="${textColor}" stroke-width="${wm.stroke}" stroke-linejoin="round">${wm.paths.map((d) => `<path d="${d}"/>`).join('')}</g>` +
    `<rect x="${wm.dot.x}" y="${wm.dot.y}" width="${wm.dot.w}" height="${wm.dot.h}" rx="${wm.dot.rx}" fill="${dotColor}"/></svg>`
  );
}
write('logo/wordmark-on-dark.svg', wordmarkSvg(B.ivory.hex, B['lagoon-bright'].hex));
write('logo/wordmark-on-light.svg', wordmarkSvg(B['ink-text'].hex, B['lagoon-deep'].hex));
write('logo/wordmark-mono-black.svg', wordmarkSvg('#000', '#000'));
write('logo/wordmark-mono-white.svg', wordmarkSvg('#fff', '#fff'));
function lockupSvg(colors, textColor, dotColor) {
  // symbol (24 grid, 16-unit-tall s spanning y 4..20) at scale k so the s = 1.45 x wordmark x-height.
  const k = 1.0;
  const v = VARIANTS.small;
  const sym = halves({ stroke: 3 });
  const gap = 7;
  const symW = 12 * k;
  const wmScale = (16 * k) / 16 / 1.3; // wordmark x-height = s height / 1.3
  const wmX = symW + gap;
  const wmY = 4 + (16 - 16 * wmScale) / 1 - 0; // baseline-align: wordmark baseline = s bottom (y 20)
  const width = wmX + wm.width * wmScale + 2;
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="5 2 ${width} 19" width="${width * 16}" height="${19 * 16}" role="img" aria-label="scrin">` +
    `<g fill="none" stroke-width="${v.stroke}" stroke-linejoin="round"><path d="${sym.ivory}" stroke="${colors[0]}"/><path d="${sym.lagoon}" stroke="${colors[1]}"/></g>` +
    `<g transform="translate(${6 + wmX} ${wmY}) scale(${wmScale})"><g fill="none" stroke="${textColor}" stroke-width="${wm.stroke}" stroke-linejoin="round">${wm.paths.map((d) => `<path d="${d}"/>`).join('')}</g>` +
    `<rect x="${wm.dot.x}" y="${wm.dot.y}" width="${wm.dot.w}" height="${wm.dot.h}" rx="${wm.dot.rx}" fill="${dotColor}"/></g></svg>`
  );
}
write('logo/lockup-horizontal-on-dark.svg', lockupSvg(DARK, B.ivory.hex, B['lagoon-bright'].hex));
write('logo/lockup-horizontal-on-light.svg', lockupSvg(LIGHT, B['ink-text'].hex, B['lagoon-deep'].hex));

// Construction drawing
{
  const s = halves({ stroke: 3 });
  let grid = '';
  for (let i = 0; i <= 24; i++) {
    const w = i % 4 === 0 ? 0.06 : 0.025;
    grid += `<line x1="${i}" y1="0" x2="${i}" y2="24" stroke="#5a7d80" stroke-width="${w}"/><line x1="0" y1="${i}" x2="24" y2="${i}" stroke="#5a7d80" stroke-width="${w}"/>`;
  }
  write(
    'logo/construction.svg',
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="-1 -1 26 28" width="1040" height="1120" role="img" aria-label="scrin mark construction">` +
      `<rect x="-1" y="-1" width="26" height="28" fill="${B.ink.hex}"/>${grid}` +
      `<rect x="6" y="4" width="12" height="16" fill="none" stroke="#e8c76a" stroke-width="0.08" stroke-dasharray="0.3 0.2"/>` +
      `<circle cx="12" cy="12" r="0.35" fill="#e8c76a"/><circle cx="12" cy="12" r="8" fill="none" stroke="#e8c76a" stroke-width="0.05"/>` +
      `<g fill="none" stroke-width="3" stroke-linejoin="round" opacity="0.9"><path d="${s.ivory}" stroke="${B.ivory.hex}"/><path d="${s.lagoon}" stroke="${B['lagoon-bright'].hex}"/></g>` +
      `<g fill="none" stroke="#e8c76a" stroke-width="0.06"><path d="${s.ivory}"/><path d="${s.lagoon}"/></g>` +
      `<g font-family="Inter, sans-serif" font-size="0.62" fill="#e8c76a"><text x="0" y="25.6">24-unit grid · stroke 3 · bars y 5.5/12/18.5 · counters 3.5 (1:1.17) · r 3 · box 12x16 · 180° symmetric about (12,12)</text>` +
      `<text x="0" y="26.5">ivory half = you · lagoon half = them · seam at x 12 (ivory overlaps 0.35 under lagoon) · mono: 1-unit gap at the seam</text></g></svg>`,
  );
}

// ---------------------------------------------------------------- 5. concepts (comparison sheet)
const concepts = {
  'A-split-s': {
    title: 'A · Split S (two halves of one s meet)',
    svg: (dark = true) => tileSvg('small', { markColors: dark ? DARK : DARK }),
    micro: () => tileSvg('micro'),
    sym: (colors) => symbolSvg('small', colors),
    microSym: (colors) => symbolSvg('micro', colors),
    mono: (c) => symbolSvg('small', [c, c], { gap: true }),
  },
  'B-twin-panes': {
    title: 'B · Twin panes (two overlapping screens)',
    body: (c1, c2) =>
      `<rect x="4.5" y="4.5" width="11" height="9" rx="2.25" fill="none" stroke="${c1}" stroke-width="2.5"/>` +
      `<rect x="9.5" y="10.5" width="10" height="9" rx="2.25" fill="${c2}"/>`,
  },
  'C-corner-brackets': {
    title: 'C · Corner brackets (capture frame + cursor)',
    body: (c1, c2) =>
      `<path d="M4.5 11V7.5A3 3 0 0 1 7.5 4.5H11" fill="none" stroke="${c1}" stroke-width="3"/>` +
      `<path d="M19.5 13V16.5A3 3 0 0 1 16.5 19.5H13" fill="none" stroke="${c2}" stroke-width="3"/>` +
      `<rect x="10" y="10" width="4" height="4" rx="1" fill="${c2}"/>`,
  },
  'D-screen-code': {
    title: 'D · Screen + one-time code dots (category default)',
    body: (c1, c2) =>
      `<rect x="3.5" y="5" width="17" height="12" rx="2.5" fill="none" stroke="${c1}" stroke-width="2.5"/>` +
      `<path d="M9 20.25h6" stroke="${c1}" stroke-width="2.5" stroke-linecap="round"/>` +
      `<circle cx="8" cy="11" r="1.4" fill="${c2}"/><circle cx="12" cy="11" r="1.4" fill="${c2}"/><circle cx="16" cy="11" r="1.4" fill="${c2}"/>`,
  },
};
function conceptTile(key, colors = DARK, tile = true) {
  const c = concepts[key];
  if (key === 'A-split-s') return tile ? tileSvg('small', { markColors: colors }) : symbolSvg('small', colors);
  const bgDefs = `<defs><linearGradient id="t" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${B['ink-hi'].hex}"/><stop offset="0.7" stop-color="${B.ink.hex}"/></linearGradient></defs><rect x="1" y="1" width="22" height="22" rx="5.25" fill="url(#t)"/>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="512" height="512">${tile ? bgDefs : ''}${c.body(...colors)}</svg>`;
}
for (const key of Object.keys(concepts)) {
  write(`concepts/${key}.svg`, conceptTile(key));
  write(`concepts/${key}-symbol-light.svg`, conceptTile(key, LIGHT, false));
}

// ---------------------------------------------------------------- 6. Android vectors
const ANDROID_SCALE = 2.75; // 16-unit s -> 44 dp tall in the 108 dp canvas (diag 55 < 66 safe circle)
const ANDROID_T = 54 - 12 * ANDROID_SCALE;
function vdPaths(src, c1, c2, names = false) {
  return (
    `    <group android:scaleX="${ANDROID_SCALE}" android:scaleY="${ANDROID_SCALE}" android:translateX="${ANDROID_T}" android:translateY="${ANDROID_T}">\n` +
    `        <path${names ? ' android:name="ivory"' : ''} android:pathData="${src.ivory}" android:strokeColor="${c1}" android:strokeWidth="${src.stroke}" android:strokeLineJoin="round" android:fillColor="#00000000"/>\n` +
    `        <path${names ? ' android:name="lagoon"' : ''} android:pathData="${src.lagoon}" android:strokeColor="${c2}" android:strokeWidth="${src.stroke}" android:strokeLineJoin="round" android:fillColor="#00000000"/>\n` +
    `    </group>`
  );
}
const VD_HEAD = `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by brand/scripts/build.mjs - do not edit by hand. -->\n<vector xmlns:android="http://schemas.android.com/apk/res/android"\n    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">\n`;
const small = halves({ stroke: 3 });
write('android/drawable/ic_launcher_foreground.xml', `${VD_HEAD}${vdPaths(small, B.ivory.hex, B['lagoon-bright'].hex)}\n</vector>`);
write('android/drawable/ic_launcher_monochrome.xml', `${VD_HEAD}${vdPaths(halves({ stroke: 3, gap: 1 }), '#FFFFFFFF', '#FFFFFFFF')}\n</vector>`);
write(
  'android/drawable/ic_launcher_background.xml',
  `${VD_HEAD}    <path android:pathData="M0,0h108v108h-108z">\n        <aapt:attr xmlns:aapt="http://schemas.android.com/aapt" name="android:fillColor">\n` +
    `            <gradient android:type="linear" android:startX="0" android:startY="0" android:endX="108" android:endY="108">\n` +
    `                <item android:offset="0" android:color="${B['ink-hi'].hex}"/>\n                <item android:offset="0.7" android:color="${B.ink.hex}"/>\n            </gradient>\n        </aapt:attr>\n    </path>\n</vector>`,
);
const ADAPTIVE = `<?xml version="1.0" encoding="utf-8"?>\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n    <background android:drawable="@drawable/ic_launcher_background"/>\n    <foreground android:drawable="@drawable/ic_launcher_foreground"/>\n    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>\n</adaptive-icon>`;
write('android/mipmap-anydpi-v26/ic_launcher.xml', ADAPTIVE);
write('android/mipmap-anydpi-v26/ic_launcher_round.xml', ADAPTIVE);
write(
  'android/values/brand_colors.xml',
  `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by brand/scripts/build.mjs. -->\n<resources>\n` +
    `    <color name="scrin_ink">${B.ink.hex}</color>\n    <color name="scrin_ivory">${B.ivory.hex}</color>\n` +
    `    <color name="scrin_lagoon">${B['lagoon-bright'].hex}</color>\n    <color name="scrin_lagoon_deep">${B['lagoon-deep'].hex}</color>\n` +
    `    <color name="scrin_splash_light">${resolve('light', 'bg.canvas').hex}</color>\n    <color name="scrin_splash_dark">${B.ink.hex}</color>\n</resources>`,
);

// ---------------------------------------------------------------- 7. motion outputs (one source)
const L = motion.logo;
const bez = (e) => `cubic-bezier(${e.$value.join(', ')})`;
const ease = bez(L.ease);
const kf = (name, frames) =>
  `@keyframes ${name} {\n${frames.map(([p, d]) => `  ${p}% { ${d} }`).join('\n')}\n}`;
const X = L.$extensions['app.scrin.logo'];
const { intro, thinking, success, error, hover, press, morph } = X;
const tr = (x, y) => `transform: translate(${x}px, ${y}px)`;
const cssKeyframes = [
  kf('scrin-draw', [[0, 'stroke-dasharray: 1 1; stroke-dashoffset: 1'], [99.9, 'stroke-dasharray: 1 1; stroke-dashoffset: 0'], [100, 'stroke-dasharray: 1 0; stroke-dashoffset: 0']]),
  kf('scrin-arrive-ivory', [[0, tr(-intro.travel, -intro.travel)], [100, tr(0, 0)]]),
  kf('scrin-arrive-lagoon', [[0, tr(intro.travel, intro.travel)], [100, tr(0, 0)]]),
  kf('scrin-chase', [[0, 'stroke-dashoffset: 0'], [100, 'stroke-dashoffset: -1']]),
  kf('scrin-lock', [[0, 'transform: scale(1)'], [40, `transform: scale(${success.scale})`], [100, 'transform: scale(1)']]),
  kf('scrin-shake', error.x.map((x, i) => [Math.round((i / (error.x.length - 1)) * 100), `transform: translateX(${x}px)`])),
  kf('scrin-part-ivory', [[0, tr(0, 0)], [50, tr(-error.part, 0)], [100, tr(0, 0)]]),
  kf('scrin-part-lagoon', [[0, tr(0, 0)], [50, tr(error.part, 0)], [100, tr(0, 0)]]),
].join('\n\n');
const cssRules = `/* scrin logo motion - generated by brand/scripts/build.mjs from tokens/motion.tokens.json (logo.*).
 * Markup: <svg viewBox="0 0 24 24"><g transform="(optical scale, optional)"><g class="scrin-mark" data-state="intro|thinking|success|error">
 *   <path class="scrin-mark__ivory" pathLength="1"/><path class="scrin-mark__lagoon" pathLength="1"/></g></g></svg>
 * Never put a transform ATTRIBUTE on .scrin-mark itself: the CSS transform of success/error replaces it.
 * Units: translate px are SVG user units of the 24-unit grid (they scale with the icon).
 * Static mark == final frame of every state. */
${cssKeyframes}

.scrin-mark, .scrin-mark path { transform-box: view-box; transform-origin: 12px 12px; }
.scrin-mark path { stroke-dasharray: 1 0; }

.scrin-mark[data-state='intro'] path { stroke-dasharray: 1; animation: scrin-draw ${intro.draw}ms ${ease} both; }
.scrin-mark[data-state='intro'] .scrin-mark__lagoon { animation-delay: ${intro.stagger}ms; }
.scrin-mark[data-state='intro'] .scrin-mark__ivory { animation: scrin-draw ${intro.draw}ms ${ease} both, scrin-arrive-ivory ${intro.draw + intro.stagger}ms ${ease} both; }
.scrin-mark[data-state='intro'] .scrin-mark__lagoon { animation: scrin-draw ${intro.draw}ms ${ease} ${intro.stagger}ms both, scrin-arrive-lagoon ${intro.draw + intro.stagger}ms ${ease} both; }

.scrin-mark[data-state='thinking'] path { stroke-dasharray: ${thinking.dash} ${1 - thinking.dash}; animation: scrin-chase ${thinking.period}ms linear ${thinking.iterations}; }
.scrin-mark[data-state='thinking'] .scrin-mark__lagoon { animation-delay: -${thinking.period / 2}ms; }

.scrin-mark[data-state='success'] { animation: scrin-lock ${success.duration}ms ${ease}; }
.scrin-mark[data-state='error'] { animation: scrin-shake ${error.duration}ms linear; }
.scrin-mark[data-state='error'] .scrin-mark__ivory { animation: scrin-part-ivory ${error.duration}ms linear; }
.scrin-mark[data-state='error'] .scrin-mark__lagoon { animation: scrin-part-lagoon ${error.duration}ms linear; }

.scrin-mark-hover path { transition: transform ${hover.duration}ms ${ease}; }
.scrin-mark-hover:hover .scrin-mark__ivory, .scrin-mark-hover:focus-visible .scrin-mark__ivory { transform: translate(${-hover.travel}px, ${-hover.travel}px); }
.scrin-mark-hover:hover .scrin-mark__lagoon, .scrin-mark-hover:focus-visible .scrin-mark__lagoon { transform: translate(${hover.travel}px, ${hover.travel}px); }
.scrin-mark-hover { transition: transform ${press.duration}ms ${ease}; }
.scrin-mark-hover:active { transform: scale(${press.scale}); }

/* Splash -> title-bar shared element (View Transitions). */
.scrin-mark-morph { view-transition-name: scrin-mark; }
::view-transition-group(scrin-mark) { animation-duration: ${morph.duration}ms; animation-timing-function: ${bez(motion.easing.move)}; }

@media (prefers-reduced-motion: reduce) {
  .scrin-mark, .scrin-mark path, .scrin-mark-hover, .scrin-mark-hover path { animation: none !important; transition: none !important; transform: none !important; stroke-dasharray: 1 0 !important; }
  .scrin-mark[data-state='thinking'] { animation: scrin-pulse ${thinking.reducedPulse}ms steps(2, jump-none) 3 !important; }
  ::view-transition-group(scrin-mark) { animation-duration: ${motion.reduced.fade.$value.value}ms; }
}
@keyframes scrin-pulse { 0% { opacity: 1 } 100% { opacity: 0.55 } }
`;
write('dist/motion/logo.css', cssRules);

// Animated SVG (intro, once), static first frame for clients without CSS animation = final mark.
write(
  'dist/motion/logo-intro.svg',
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="256" height="256" role="img" aria-label="scrin">` +
    `<style>${kf('scrin-draw', [[0, 'stroke-dashoffset: 1'], [100, 'stroke-dashoffset: 0']])}` +
    `${kf('a', [[0, tr(-intro.travel, -intro.travel)], [100, tr(0, 0)]])}${kf('b', [[0, tr(intro.travel, intro.travel)], [100, tr(0, 0)]])}` +
    `.i{stroke-dasharray:1;animation:scrin-draw ${intro.draw}ms ${ease} both,a ${intro.draw + intro.stagger}ms ${ease} both}` +
    `.l{stroke-dasharray:1;animation:scrin-draw ${intro.draw}ms ${ease} ${intro.stagger}ms both,b ${intro.draw + intro.stagger}ms ${ease} both}` +
    `@media (prefers-reduced-motion: reduce){.i,.l{animation:none;stroke-dasharray:none}}</style>` +
    `<g fill="none" stroke-width="3" stroke-linejoin="round" transform="translate(12 12) scale(0.86) translate(-12 -12)">` +
    `<path class="i" pathLength="1" d="${small.ivory}" stroke="${B.ivory.hex}"/><path class="l" pathLength="1" d="${small.lagoon}" stroke="${B['lagoon-bright'].hex}"/></g></svg>`,
);
write(
  'dist/motion/logo-thinking.svg',
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="256" height="256" role="img" aria-label="scrin is working">` +
    `<style>${kf('c', [[0, 'stroke-dashoffset: 0'], [100, 'stroke-dashoffset: -1']])}` +
    `path{stroke-dasharray:${thinking.dash} ${1 - thinking.dash};animation:c ${thinking.period}ms linear infinite}.l{animation-delay:-${thinking.period / 2}ms}` +
    `@media (prefers-reduced-motion: reduce){path{animation:none;stroke-dasharray:none}}</style>` +
    `<g fill="none" stroke-width="3" stroke-linejoin="round" transform="translate(12 12) scale(0.86) translate(-12 -12)">` +
    `<path pathLength="1" d="${small.ivory}" stroke="${B.ivory.hex}"/><path class="l" pathLength="1" d="${small.lagoon}" stroke="${B['lagoon-bright'].hex}"/></g></svg>`,
);

// Motion 14 (motion/react) variants.
write(
  'dist/motion/logo-motion.ts',
  `// Generated by brand/scripts/build.mjs from tokens/motion.tokens.json (logo.*). Do not edit.
// Usage (motion/react): <motion.path d={SCRIN_MARK.ivory} variants={ivoryVariants} initial="hidden" animate={state} />
// Honour reduced motion with <MotionConfig reducedMotion="user"> - transforms then resolve instantly.
import type { Variants } from 'motion/react';

export const SCRIN_MARK = { viewBox: '0 0 24 24', stroke: 3, ivory: '${small.ivory}', lagoon: '${small.lagoon}' } as const;
export const SCRIN_COLORS = { ivory: '${B.ivory.hex}', lagoon: '${B['lagoon-bright'].hex}', ink: '${B.ink.hex}', inkText: '${B['ink-text'].hex}', lagoonDeep: '${B['lagoon-deep'].hex}' } as const;
const ease = [${L.ease.$value.join(', ')}] as const;

export const ivoryVariants: Variants = {
  hidden: { pathLength: 0, x: ${-intro.travel}, y: ${-intro.travel} },
  intro: { pathLength: 1, x: 0, y: 0, transition: { duration: ${intro.draw / 1000}, ease } },
  idle: { pathLength: 1, x: 0, y: 0 },
  hover: { x: ${-hover.travel}, y: ${-hover.travel}, transition: { duration: ${hover.duration / 1000}, ease } },
  error: { x: [0, ${-error.part}, 0], transition: { duration: ${error.duration / 1000} } },
};
export const lagoonVariants: Variants = {
  hidden: { pathLength: 0, x: ${intro.travel}, y: ${intro.travel} },
  intro: { pathLength: 1, x: 0, y: 0, transition: { duration: ${intro.draw / 1000}, delay: ${intro.stagger / 1000}, ease } },
  idle: { pathLength: 1, x: 0, y: 0 },
  hover: { x: ${hover.travel}, y: ${hover.travel}, transition: { duration: ${hover.duration / 1000}, ease } },
  error: { x: [0, ${error.part}, 0], transition: { duration: ${error.duration / 1000} } },
};
export const markVariants: Variants = {
  idle: { scale: 1, x: 0 },
  success: { scale: [1, ${success.scale}, 1], transition: { duration: ${success.duration / 1000}, times: [0, 0.4, 1], ease } },
  error: { x: [${error.x.join(', ')}], transition: { duration: ${error.duration / 1000}, ease: 'linear' } },
  press: { scale: ${press.scale}, transition: { duration: ${press.duration / 1000}, ease } },
};
/** thinking: animate pathOffset on both paths, lagoon half a period behind. */
export const THINKING = { period: ${thinking.period / 1000}, dash: ${thinking.dash}, iterations: ${thinking.iterations} } as const;
export const MORPH = { layoutId: 'scrin-mark', duration: ${morph.duration / 1000}, ease: [${motion.easing.move.$value.join(', ')}] } as const;
`,
);

// Android AVD splash (<= 1000 ms): trim-path draw, staggered.
write(
  'android/drawable/avd_scrin_splash.xml',
  `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by brand/scripts/build.mjs from motion.tokens.json logo.intro. ${intro.draw + intro.stagger} ms total (<= 1000 ms splash budget). -->\n` +
    `<animated-vector xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt">\n` +
    `    <aapt:attr name="android:drawable">\n${VD_HEAD.split('\n').slice(2).join('\n').replace(/^/gm, '        ')}${vdPaths(small, B.ivory.hex, B['lagoon-bright'].hex, true).replace(/^/gm, '    ')}\n        </vector>\n    </aapt:attr>\n` +
    ['ivory', 'lagoon']
      .map(
        (n, i) =>
          `    <target android:name="${n}">\n        <aapt:attr name="android:animation">\n            <objectAnimator android:propertyName="trimPathEnd" android:valueFrom="0" android:valueTo="1" android:valueType="floatType"\n                android:duration="${intro.draw}" android:startOffset="${i * intro.stagger}">\n                <aapt:attr name="android:interpolator"><pathInterpolator android:controlX1="${L.ease.$value[0]}" android:controlY1="${L.ease.$value[1]}" android:controlX2="${L.ease.$value[2]}" android:controlY2="${L.ease.$value[3]}"/></aapt:attr>\n            </objectAnimator>\n        </aapt:attr>\n    </target>`,
      )
      .join('\n') +
    `\n</animated-vector>`,
);

// ---------------------------------------------------------------- 8. CSS / Kotlin token outputs
const cssVars = (theme) =>
  Object.keys(semantic[theme])
    .map((slot) => `  --brand-${slot.replace('.', '-')}: ${ok(resolve(theme, slot))}; /* ${resolve(theme, slot).hex} */`)
    .join('\n');
write(
  'dist/css/brand.css',
  `/* scrin brand tokens - generated by brand/scripts/build.mjs. Consumers import this file, never hex literals. */\n` +
    `:root, [data-mode='light'] {\n${cssVars('light')}\n}\n[data-mode='dark'] {\n${cssVars('dark')}\n}\n[data-mode='dark'][data-surface='amoled'] { --brand-bg-canvas: oklch(0 0 0); }\n` +
    `:root {\n${Object.entries(B).map(([k, c]) => `  --brand-${k}: ${ok(c)}; /* ${c.hex} */`).join('\n')}\n` +
    `  --brand-font-sans: 'Inter Variable', 'Segoe UI Variable', system-ui, sans-serif;\n  --brand-font-mono: 'JetBrains Mono Variable', 'Cascadia Mono', ui-monospace, monospace;\n}\n` +
    `@font-face { font-family: 'Inter Variable'; font-style: normal; font-display: swap; font-weight: 100 900; src: url('../../fonts/Inter-latin.woff2') format('woff2-variations'); unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD; }\n` +
    `@font-face { font-family: 'Inter Variable'; font-style: normal; font-display: swap; font-weight: 100 900; src: url('../../fonts/Inter-latin-ext.woff2') format('woff2-variations'); unicode-range: U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF; }\n`,
);
const kt = (c) => `Color(0xFF${c.hex.slice(1).toUpperCase()})`;
write(
  'dist/kotlin/BrandTokens.kt',
  `// Generated by brand/scripts/build.mjs - do not edit.\npackage app.scrin.brand\n\nimport androidx.compose.ui.graphics.Color\n\nobject BrandTokens {\n` +
    Object.entries(B).map(([k, c]) => `    val ${k.replace(/-(\w)/g, (_, x) => x.toUpperCase())} = ${kt(c)}`).join('\n') +
    `\n    const val ACCENT_HUE = ${HUE}f\n    const val ACCENT_CHROMA = ${CHROMA}f\n}\n` +
    ['light', 'dark']
      .map(
        (t) =>
          `\nobject Brand${t[0].toUpperCase() + t.slice(1)} {\n` +
          Object.keys(semantic[t]).map((s) => `    val ${s.replace(/[.-](\w)/g, (_, x) => x.toUpperCase())} = ${kt(resolve(t, s))}`).join('\n') +
          `\n}`,
      )
      .join('\n'),
);
write(
  'dist/ts/tokens.ts',
  `// Generated by brand/scripts/build.mjs - do not edit.\nexport const BRAND_ACCENT = { hue: ${HUE}, chroma: ${CHROMA} } as const;\nexport const BRAND_COLORS = ${JSON.stringify(Object.fromEntries(Object.entries(B).map(([k, c]) => [k, { oklch: ok(c), hex: c.hex }])), null, 2)} as const;\nexport const BRAND_SEMANTIC = ${JSON.stringify(Object.fromEntries(['light', 'dark'].map((t) => [t, Object.fromEntries(Object.keys(semantic[t]).map((s) => [s, resolve(t, s).hex]))])), null, 2)} as const;\n`,
);

// Expose geometry + colours for render.mjs / sheet.
write(
  'dist/build-manifest.json',
  JSON.stringify({ hue: HUE, chroma: CHROMA, tint: TINT, colors: Object.fromEntries(Object.entries(B).map(([k, c]) => [k, c.hex])), dark: DARK, light: LIGHT, concepts: Object.fromEntries(Object.entries(concepts).map(([k, v]) => [k, v.title])), written }, null, 2),
);
console.log(`build.mjs: wrote ${written.length} files`);
